kind: Deployment
apiVersion: apps/v1
metadata:
  name: studi-frontend
  namespace: default
  generation: 1
  labels:
    app: studi-frontend
  annotations:
    deployment.kubernetes.io/revision: '1'
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: apps/v1
     
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      subresource: status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxv1
  template:
    metadata:
      labels:
        app: nginxv1
    spec:
      containers:
        - name: nginx
          image: nginx:latest
status:
  observedGeneration: 1
  replicas: 1